export const products = [
  {
    id: 1,
    title: 'Rice meals',
    price: 2000,
    description:
      'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Reiciendis recusandae quibusdam iure, odit consectetur veritatis, eum a officiis, fugiat dignissimos itaque laboriosam odio! Adipisci, recusandae fuga eum dolorum nobis mollitia.',
    discount: 10,
    favourite: true,
    rating: 5,
    image_url: '../assets/images/rice.png',
    cooke_time: '40-50',
  },
  {
    id: 2,
    title: 'Protein meals',
    price: 5000,
    description:
      'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Reiciendis recusandae quibusdam iure, odit consectetur veritatis, eum a officiis, fugiat dignissimos itaque laboriosam odio! Adipisci, recusandae fuga eum dolorum nobis mollitia.',
    discount: 10,
    favourite: false,
    rating: 5,
    image_url: '../assets/images/meat.png',
    cooke_time: '40-50',
  },
  {
    id: 3,
    title: 'Soup',
    price: 6000,
    description:
      'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Reiciendis recusandae quibusdam iure, odit consectetur veritatis, eum a officiis, fugiat dignissimos itaque laboriosam odio! Adipisci, recusandae fuga eum dolorum nobis mollitia.',
    discount: 2,
    favourite: false,
    rating: 5,
    image_url: '../assets/images/soup.png',
    cooke_time: '40-50',
  },
  {
    id: 4,
    title: 'Rice meals',
    price: 2000,
    description:
      'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Reiciendis recusandae quibusdam iure, odit consectetur veritatis, eum a officiis, fugiat dignissimos itaque laboriosam odio! Adipisci, recusandae fuga eum dolorum nobis mollitia.',
    discount: 10,
    favourite: true,
    rating: 5,
    image_url: '../assets/images/rice.png',
    cooke_time: '40-50',
  },
  {
    id: 5,
    title: 'Protein meals',
    price: 5000,
    description:
      'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Reiciendis recusandae quibusdam iure, odit consectetur veritatis, eum a officiis, fugiat dignissimos itaque laboriosam odio! Adipisci, recusandae fuga eum dolorum nobis mollitia.',
    discount: 10,
    favourite: false,
    rating: 5,
    image_url: '../assets/images/meat.png',
    cooke_time: '40-50',
  },

  {
    id: 6,
    title: 'Soup',
    price: 6000,
    description:
      'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Reiciendis recusandae quibusdam iure, odit consectetur veritatis, eum a officiis, fugiat dignissimos itaque laboriosam odio! Adipisci, recusandae fuga eum dolorum nobis mollitia.',
    discount: 2,
    favourite: false,
    rating: 5,
    image_url: '../assets/images/soup.png',
    cooke_time: '40-50',
  },
  {
    id: 12,
    title: 'Soup',
    price: 6000,
    description:
      'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Reiciendis recusandae quibusdam iure, odit consectetur veritatis, eum a officiis, fugiat dignissimos itaque laboriosam odio! Adipisci, recusandae fuga eum dolorum nobis mollitia.',
    discount: 2,
    favourite: false,
    rating: 5,
    image_url: '../assets/images/soup.png',
    cooke_time: '40-50',
  },
  {
    id: 8,
    title: 'Protein meals',
    price: 5000,
    description:
      'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Reiciendis recusandae quibusdam iure, odit consectetur veritatis, eum a officiis, fugiat dignissimos itaque laboriosam odio! Adipisci, recusandae fuga eum dolorum nobis mollitia.',
    discount: 10,
    favourite: false,
    rating: 5,
    image_url: '../assets/images/meat.png',
    cooke_time: '40-50',
  },
  {
    id: 7,
    title: 'Rice meals',
    price: 2000,
    description:
      'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Reiciendis recusandae quibusdam iure, odit consectetur veritatis, eum a officiis, fugiat dignissimos itaque laboriosam odio! Adipisci, recusandae fuga eum dolorum nobis mollitia.',
    discount: 10,
    favourite: true,
    rating: 5,
    image_url: '../assets/images/rice.png',
    cooke_time: '40-50',
  },
  {
    id: 11,
    title: 'Protein meals',
    price: 5000,
    description:
      'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Reiciendis recusandae quibusdam iure, odit consectetur veritatis, eum a officiis, fugiat dignissimos itaque laboriosam odio! Adipisci, recusandae fuga eum dolorum nobis mollitia.',
    discount: 10,
    favourite: false,
    rating: 5,
    image_url: '../assets/images/meat.png',
    cooke_time: '40-50',
  },
  {
    id: 9,
    title: 'Soup',
    price: 6000,
    description:
      'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Reiciendis recusandae quibusdam iure, odit consectetur veritatis, eum a officiis, fugiat dignissimos itaque laboriosam odio! Adipisci, recusandae fuga eum dolorum nobis mollitia.',
    discount: 2,
    favourite: false,
    rating: 5,
    image_url: '../assets/images/soup.png',
    cooke_time: '40-50',
  },
  {
    id: 10,
    title: 'Rice meals',
    price: 2000,
    description:
      'Lorem ipsum, dolor sit amet consectetur adipisicing elit. Reiciendis recusandae quibusdam iure, odit consectetur veritatis, eum a officiis, fugiat dignissimos itaque laboriosam odio! Adipisci, recusandae fuga eum dolorum nobis mollitia.',
    discount: 10,
    favourite: true,
    rating: 5,
    image_url: '../assets/images/rice.png',
    cooke_time: '40-50',
  },
];
